setClass("Model", slots = c(
  name = "character",
  description = "character",
  settings = "list",
  fit = "ANY",
  transforms = "list",
  dropped = "logical",
  coefs = "numeric",
  inmodel = "logical",
  contribution = "numeric",
  ks = "numeric"))
